stages:
  - test
  - python37

variables:
  PROJECT_NAME: algorithmia-python
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  RUNNING_ON_BUILD_SERVER: "true"

test:
  stage: test
  script:
    - if [ -z $ALGORITHMIA_API_KEY ]; then echo "Algorithmia API key not defined"; exit 1; fi

test:pylint:36:
  image: python:3.6
  script:
    - pip install pylint --quiet
    - pylint --ignored-classes=_socketobject *.py || echo $?

test:pytest:36:
  image: python:3.6
  script:
    - pip install -r requirements.txt --quiet
    - pip install pytest --quiet
    - pytest


python37:
  stage: python37
  image: python:3.7
  script:
    - pip install -r requirements.txt --quiet
    - pip install pytest --quiet
    - pytest

#test:pytest:38:
#  image: python:3.8
#  script:
#    - pip install -r requirements.txt --quiet
#    - pip install pytest --quiet
#    - pytest
#
#test:pytest:39:
#  image: python:3.9
#  script:
#    - pip install -r requirements.txt --quiet
#    - pip install pytest --quiet
#    - pytest
#
#test:pytest:27:
#  image: python:2.7
#  script:
#    - pip install -r requirements.txt --quiet
#    - pip install pytest --quiet
#    - pytest
#
